# Generated by Django 3.2.6 on 2022-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_a_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drink_metric',
            field=models.CharField(default='Ml', max_length=400),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drink_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
