# Generated by Django 3.2.6 on 2021-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='ingredients_list',
            new_name='small_note',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='thumbnail_image',
            field=models.FileField(default='abc.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
