# Generated by Django 3.2.6 on 2021-08-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210805_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_status',
            field=models.CharField(default='Ordered', max_length=500),
        ),
    ]
