# Generated by Django 3.2.6 on 2022-11-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221122_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ManyToManyField(to='api.FoodCategory'),
        ),
    ]
