# Generated by Django 3.2.6 on 2022-11-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221122_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='drinks_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='metrics',
            field=models.CharField(blank=True, choices=[('Ml', 'Ml')], default='Ml', max_length=500),
        ),
    ]
