# Generated by Django 3.2.6 on 2022-11-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_drinkitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Completed', 'Order Completed'), ('Order Paid', 'Order Paid'), ('Order Cancled', 'Order Cancled')], default='Order Placed', max_length=400),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ManyToManyField(to='api.Order'),
        ),
    ]
