# Generated by Django 3.2.6 on 2022-11-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('api', '0004_auto_20221122_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod'),
        ),
    ]
