# Generated by Django 3.2.6 on 2021-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Verifying', 'Verifying'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=500),
        ),
    ]
