# Generated by Django 3.2.6 on 2022-11-22 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221122_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='drinks_quantity',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='metrics',
        ),
    ]
