# Generated by Django 3.2.6 on 2021-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210822_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Manually Paid', 'Manually Paid'), ('Esewa', 'Esewa'), ('Mobile Banking', 'Mobile Banking'), ('Paypal', 'Paypal'), ('Others', 'Others')], default='Manually Paid', max_length=500),
        ),
    ]
