# Generated by Django 3.2.6 on 2022-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_canclepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cancle_reason',
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Number', 'Number')], default='Number', max_length=400),
        ),
        migrations.AlterField(
            model_name='canclepayment',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Payment Canceled', 'Payment Canceled')], default='Payment Canceled', max_length=400),
        ),
    ]
