# Generated by Django 3.2.6 on 2022-11-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_payment_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
