# Generated by Django 3.2.6 on 2022-11-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_payment_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paidd',
            field=models.FloatField(default=0),
        ),
    ]
