# Generated by Django 3.2.6 on 2023-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_payment_amount_paidd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='drink_metric',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='drink_quantity',
        ),
        migrations.AddField(
            model_name='drinkitem',
            name='type_of_drink',
            field=models.CharField(blank=True, choices=[('Hard Drink', 'Hard Drink'), ('Soft Drink', 'Soft Drink'), ('Beer', 'Beer'), ('Wine', 'Wine')], max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='drink_metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Qtr', 'Qtr'), ('Half', 'Half'), ('Full', 'Full'), ('Glass', 'Glass'), ('Bootle', 'Bottle'), ('Beer Bottle Small', 'Beer Bottle Small')], default='Ml', max_length=400),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='drink_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type_of_drink',
            field=models.CharField(choices=[('Hard Drink', 'Hard Drink'), ('Soft Drink', 'Soft Drink'), ('Beer', 'Beer'), ('Wine', 'Wine')], default='Soft Drink', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='is_kot_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Order Completed', 'Order Completed'), ('Order Paid', 'Order Paid'), ('Order Canceled', 'Order Canceled'), ('Payment Canceled', 'Payment Canceled')], default='Ordered', max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='payment',
            name='pan_no',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tender_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(related_name='orderitems', to='api.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='no_of_items',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Payment Canceled', 'Payment Canceled'), ('Payment Credited', 'Payment Credited')], default='Unpaid', max_length=400),
        ),
    ]
