# Generated by Django 3.2.6 on 2022-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_payment_amount_paidd'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_remarks',
            field=models.TextField(blank=True),
        ),
    ]
