# Generated by Django 3.2.6 on 2022-11-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_payment_payment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_kot_printed',
            field=models.BooleanField(default=False),
        ),
    ]
