# Generated by Django 3.2.6 on 2022-11-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_is_kot_printed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created',)},
        ),
    ]
