# Generated by Django 3.2.6 on 2022-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20221126_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='drink_metric',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='drink_quantity',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='drink_metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Qtr', 'Qtr'), ('Half', 'Half'), ('Full', 'Full')], default='Ml', max_length=400),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='drink_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
