# Generated by Django 3.2.6 on 2022-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20221130_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='no_of_items',
            field=models.IntegerField(default=1),
        ),
    ]
