# Generated by Django 3.2.6 on 2022-12-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_orderitem_no_of_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Order Completed', 'Order Completed'), ('Order Paid', 'Order Paid'), ('Order Canceled', 'Order Canceled'), ('Payment Canceled', 'Payment Canceled')], default='Ordered', max_length=500),
        ),
    ]
