# Generated by Django 3.2.6 on 2022-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20221201_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkitem',
            name='type_of_drink',
            field=models.CharField(blank=True, choices=[('Hard Drink', 'Hard Drink'), ('Soft Drink', 'Soft Drink'), ('Beer', 'Beer')], max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type_of_drink',
            field=models.CharField(choices=[('Hard Drink', 'Hard Drink'), ('Soft Drink', 'Soft Drink'), ('Beer', 'Beer')], default='Soft Drink', max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='drink_metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Qtr', 'Qtr'), ('Half', 'Half'), ('Full', 'Full'), ('1 Glass', '1 Glass'), ('1 Bootle', '1 Bottle')], default='Ml', max_length=400),
        ),
    ]
