# Generated by Django 3.2.6 on 2022-12-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20221203_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='drink_metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Qtr', 'Qtr'), ('Half', 'Half'), ('Full', 'Full'), ('1_Glass', '1_Glass'), ('1_Bootle', '1_Bottle')], default='Ml', max_length=400),
        ),
    ]
