# Generated by Django 3.2.6 on 2022-12-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_fooditem_drink_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='drink_metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Qtr', 'Qtr'), ('Half', 'Half'), ('Full', 'Full'), ('1 Glass', '1 Glass'), ('1 Bootle', '1 Bottle')], default='Ml', max_length=400),
        ),
    ]
