# Generated by Django 3.2.6 on 2023-01-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_fooditem_drink_metric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='payment',
            name='pan_no',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='payment',
            name='tender_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='type_of_drink',
            field=models.CharField(blank=True, choices=[('Hard Drink', 'Hard Drink'), ('Soft Drink', 'Soft Drink'), ('Beer', 'Beer'), ('Wine', 'Wine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='drink_metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Qtr', 'Qtr'), ('Half', 'Half'), ('Full', 'Full'), ('Glass', 'Glass'), ('Bootle', 'Bottle'), ('Beer Bottle Small', 'Beer Bottle Small')], default='Ml', max_length=400),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='type_of_drink',
            field=models.CharField(choices=[('Hard Drink', 'Hard Drink'), ('Soft Drink', 'Soft Drink'), ('Beer', 'Beer'), ('Wine', 'Wine')], default='Soft Drink', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(related_name='orderitems', to='api.OrderItem'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Payment Canceled', 'Payment Canceled'), ('Payment Credited', 'Payment Credited')], default='Unpaid', max_length=400),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
    ]
