# Generated by Django 3.2.6 on 2023-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230124_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canclepayment',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='canclepayment',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='drinkitem',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='table',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='updated'),
        ),
    ]
