# Generated by Django 3.2.6 on 2022-11-22 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221122_0214'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinksPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(default='Cash', max_length=500)),
                ('quantity', models.IntegerField()),
                ('metric', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('purchase_bill', models.FileField(blank=True, upload_to='')),
                ('remarks', models.TextField(blank=True)),
                ('drinkk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fooditem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
