# Generated by Django 3.2.6 on 2022-11-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_drinkitem'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkspurchase',
            name='drinkk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drinkitem'),
        ),
    ]
