# Generated by Django 3.2.6 on 2022-11-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_drinkspurchase_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkspurchase',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml')], default='Ml', max_length=100),
        ),
    ]
