# Generated by Django 3.2.6 on 2022-12-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_orderitem_no_of_items'),
        ('inventory', '0004_alter_drinkspurchase_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinksStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('metric', models.CharField(choices=[('Ml', 'Ml')], default='Ml', max_length=100)),
                ('drinkk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drinkitem')),
            ],
        ),
    ]
