# Generated by Django 3.2.6 on 2023-01-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230126_1313'),
        ('inventory', '0004_alter_drinkspurchase_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=500)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='drinkspurchase',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Paid', max_length=500),
        ),
        migrations.AlterField(
            model_name='drinkspurchase',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Beer Bottles Small', 'Beer Bottles Small'), ('Beer Bottles', 'Beer Bottles'), ('Apple Cider Bottles', 'Apple Cider Bottles'), ('Soft Drink Bottles [0.5 Ltr]', 'Soft Drink Bottles [0.5 Ltr]'), ('Soft Drink Bottles [1 Ltr]', 'Soft Drink Bottles [1 Ltr]'), ('Soft Drink Bottles [1.5 Ltr]', 'Soft Drink Bottles [1.5 Ltr]'), ('Soft Drink Bottles [2 Ltr]', 'Soft Drink Bottles [2 Ltr]')], default='Ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='drinkspurchase',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Ltr', 'Ltr'), ('Kg', 'Kg'), ('mg', 'mg'), ('Packets', 'Packets')], default='Kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='DrinksStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('metric', models.CharField(choices=[('Ml', 'Ml'), ('Beer Bottles', 'Beer Bottles'), ('Beer Bottles Small', 'Beer Bottles Small'), ('Apple Cider Bottles', 'Apple Cider Bottles')], default='Ml', max_length=100)),
                ('drinkk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drinkitem')),
            ],
        ),
    ]
