# Generated by Django 3.2.6 on 2022-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_drinksstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Ltr', 'Ltr'), ('Kg', 'Kg'), ('Packets', 'Packets')], default='Kg', max_length=100),
        ),
    ]
