# Generated by Django 3.2.6 on 2022-12-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_purchase_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Ltr', 'Ltr'), ('Kg', 'Kg'), ('mg', 'mg'), ('Packets', 'Packets')], default='Kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
