# Generated by Django 3.2.6 on 2022-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20221203_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkspurchase',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Beer_Bootles_Full', 'Beer_Bootles_Full'), ('Beer_Bootles_Half', 'Beer_Bootles_Half'), ('Soft_Drink_Bottles [0.5 Ltr]', 'Soft_Drink_Bottles [0.5 Ltr]'), ('Soft_Drink_Bottles [1 Ltr]', 'Soft_Drink_Bottles [1 Ltr]'), ('Soft_Drink_Bottles [1.5 Ltr]', 'Soft_Drink_Bottles [1.5 Ltr]'), ('Soft_Drink_Bottles [2 Ltr]', 'Soft_Drink_Bottles [2 Ltr]')], default='Ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='drinkspurchase',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='drinksstock',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Beer_Bootles_Full', 'Beer_Bootles_Full'), ('Beer_Bootles_Half', 'Beer_Bootles_Half'), ('Soft_Drink_Bottles [0.5 Ltr]', 'Soft_Drink_Bottles [0.5 Ltr]'), ('Soft_Drink_Bottles [1 Ltr]', 'Soft_Drink_Bottles [1 Ltr]'), ('Soft_Drink_Bottles [1.5 Ltr]', 'Soft_Drink_Bottles [1.5 Ltr]'), ('Soft_Drink_Bottles [2 Ltr]', 'Soft_Drink_Bottles [2 Ltr]')], default='Ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='drinksstock',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
