# Generated by Django 3.2.6 on 2023-01-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20221204_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkspurchase',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Paid', max_length=500),
        ),
        migrations.AlterField(
            model_name='drinkspurchase',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Beer Bottles Small', 'Beer Bottles Small'), ('Beer Bottles', 'Beer Bottles'), ('Apple Cider Bottles', 'Apple Cider Bottles'), ('Soft Drink Bottles [0.5 Ltr]', 'Soft Drink Bottles [0.5 Ltr]'), ('Soft Drink Bottles [1 Ltr]', 'Soft Drink Bottles [1 Ltr]'), ('Soft Drink Bottles [1.5 Ltr]', 'Soft Drink Bottles [1.5 Ltr]'), ('Soft Drink Bottles [2 Ltr]', 'Soft Drink Bottles [2 Ltr]')], default='Ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='drinksstock',
            name='metric',
            field=models.CharField(choices=[('Ml', 'Ml'), ('Beer Bottles', 'Beer Bottles'), ('Beer Bottles Small', 'Beer Bottles Small'), ('Apple Cider Bottles', 'Apple Cider Bottles')], default='Ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
