# Generated by Django 3.2.6 on 2023-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20230124_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkspurchase',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
