from django.urls import path, include
from .views import (
    foodlists,
    submitcart,
    orderslists,
    categorylists,
    foodlists_search,
    paymentt,
    tablelists,
    addTable,
    updateTable,
    deleteTable,
    singleTable,
    vatlists,
    taxlists,
    vatandtaxlists,
    addTax,
    updateTax,
    deleteTax,
    singleTax,
    addVat,
    updateVat,
    deleteVat,
    singleVat,
    CustomAuthToken,
)

urlpatterns = [
    path("foodlists/", foodlists),
    path("foodlists_search/", foodlists_search),
    path("categorylists/", categorylists),
    path("orderslists/", orderslists),
    path("submitcart/", submitcart),
    path("payorders/", paymentt),
    path("tablelists/", tablelists),
    path("add-table/", addTable),
    path("table-single/<int:id>/", singleTable),
    path("update-table/", updateTable),
    path("delete-table/", deleteTable),
    path("vat-and-tax/", vatandtaxlists),
    path("vats/", vatlists),
    path("taxes/", taxlists),
    path("add-vat/", addVat),
    path("vat-single/<int:id>/", singleVat),
    path("update-vat/", updateVat),
    path("delete-vat/", deleteVat),
    path("add-tax/", addTax),
    path("tax-single/<int:id>/", singleTax),
    path("update-tax/", updateTax),
    path("delete-tax/", deleteTax),
    path("inventory/", include("inventory.urls")),
    path("payment/", include("payments.urls")),
    path("api-token-auth/", CustomAuthToken.as_view(), name="api_token_auth"),
]
